< //
SlateportCity_OceanicMuseum_2F_Text_ThankYouForTheParts: @ 820BD8D
	.string "Yes? If you're looking for STERN,\n"
	.string "that would be me.\p"
	.string "Ah! Those must be the data I\n"
	.string "requested from the UNIVERSITY.\p"
	.string "Thank you! That's great!\n"
	.string "We can prepare for our expedition now.$"

SlateportCity_OceanicMuseum_2F_Text_WellTakeThoseParts: @ 820BE40
	.string "Hehehe, hold it!\n"
	.string "We'll take that FLASHDRIVE!$"

SlateportCity_OceanicMuseum_2F_Text_SternWhoAreYou: @ 820BE69
	.string "CAPT. STERN: Wh-what?\n"
	.string "Who are you people?$"

SlateportCity_OceanicMuseum_2F_Text_WereTeamAqua: @ 820BE93
	.string "We're TEAM AQUA!\p"
	.string "Our BOSS wants that information!\n"
	.string "Shut your yap and fork it over!$"

SlateportCity_OceanicMuseum_2F_Text_Grunt1Defeat: @ 820BEE2
// >

< //
SlateportCity_OceanicMuseum_2F_Text_SternThankYouForSavingUs: @ 820C2BE
	.string "CAPT. STERN: You're…\n"
	.string "Ah, okay, you're {PLAYER}{KUN}…\p"
	.string "Anyway, that was a tense situation!\n"
	.string "Thank you for saving us!\p"
	.string "Oh, yes, I almost forgot that you\n"
	.string "even brought the FLASHDRIVE!$"

SlateportCity_OceanicMuseum_2F_Text_SternIveGotToGo: @ 820C36C
// >