< //
#define ABILITY_NEUROFORCE 234
#define ABILITY_FLUTTER 235
#define ABILITY_BONANZA 236
#define ABILITY_PUNK_ROCK 237
#define ABILITY_SOARING_WINGS 238

#define ABILITIES_COUNT_GEN7 239
// >