< //
RustboroCity_Gym_Text_GymGuideAdvice: @ 821309D
	.string "Yo, how's it going?\p"
	.string "Listen, my friend!\n"
	.string "The ROCK type is very durable, but\l"
	.string "it can't stand WATER-type and\l"
	.string "GRASS-type moves.\p"
	.string "Well, go for it!$"

RustboroCity_Gym_Text_GymGuidePostVictory: @ 82132E2
	.string "Whoa! What a breathtaking victory!\n"
	.string "My cheering must've worked!$"

RustboroCity_Gym_Text_JoshIntro: @ 82133E9
// >