< //
    [MAPSEC_INSIDE_OF_TRUCK] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_SILENT_FOREST] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_BRINE_BEACH] = MAPPOPUP_THEME_UNDERWATER,
    [MAPSEC_SKY_PILLAR] = MAPPOPUP_THEME_STONE,
// >