< //
    [MAPSEC_NAVEL_ROCK - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_STONE,
    [MAPSEC_SILENT_FOREST] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_BRINE_BEACH] = MAPPOPUP_THEME_UNDERWATER,
    [MAPSEC_TRAINER_HILL - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE
// >