< //
VerdanturfTown_Text_MakeBattleTentDebut: @ 81EB7E2
	.string "The POKéMON BREEDER CLUB is in that\n"
	.string "red house over there.\p"
	.string "You should visit it if you are\n"
	.string "interested in raising POKéMON.$"

VerdanturfTown_EventScript_BugTypeTrainer::
	faceplayer
	questmenu QUEST_MENU_CHECK_UNLOCKED SIDE_QUEST_10
	release
	end
	
VerdanturfTown_Text_GuyTryingToBustThroughCave: @ 81EB854
// >

< //
VerdanturfTown_Text_BattleTentSign: @ 81EBA1F
	.string "POKéMON BREEDER CLUB$"

VerdanturfTown_Text_RusturfTunnelSign: @ 81EBA59
// >