< //
    [MAPSEC_NAVEL_ROCK - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_STONE,
    [MAPSEC_TRAINER_HILL - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_SILENT_FOREST - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_MYSTERY_SPRINGS - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_STONE,
    [MAPSEC_NEW_ISLAND - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_STONE,
    [MAPSEC_NEW_ISLAND2 - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_WOOD,
    [MAPSEC_RHYOLITE_CANYON - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_MARBLE,
    [MAPSEC_BRINE_BEACH - KANTO_MAPSEC_COUNT] = MAPPOPUP_THEME_UNDERWATER
};

static const u8 gText_PyramidFloor1[] = _("PYRAMID FLOOR 1");
// >