< //
SlateportCity_OceanicMuseum_1F_Text_RememberMeTakeThis: @ 820B3AB
	.string "Aiyeeeh!\n"
	.string "I didn't steal nothing!\p"
	.string "Here, take this!\n"
	.string "You saw nothing, understand!$"

SlateportCity_OceanicMuseum_1F_Text_HopeINeverSeeYouAgain: @ 820B449
	.string "That TM, it suits you more than it\n"
	.string "does me.\p"
	.string "Hope I never see you again!\n"
	.string "Wahahaha!$"

SlateportCity_OceanicMuseum_1F_Text_YouHaveToTakeThis: @ 820B49B
	.string "Awww, come on!\n"
	.string "You have to take this and let me go!$"

SlateportCity_OceanicMuseum_1F_Text_WhirlpoolExperiment: @ 820B4CF
// >