< //
#define EGG_LVL_UP_MOVES_ARRAY_COUNT    (MAX_LEVEL_UP_MOVES > 50 ? MAX_LEVEL_UP_MOVES : 50)
#define DESTINY_KNOT_INHERITED_IV_COUNT 5
#define FATEFUL_KNOT_INHERITED_IV_COUNT 6

#endif //GUARD_DAYCARE_CONSTANTS_H
// >