< //
Route103_Text_PeteIntro: @ 8295063
	.string "Go go go! No pain, no gain!$"

Route103_Text_PeteDefeated: @ 8295093
	.string "Urgh. So much pain but no gain…$"

Route103_Text_PetePostBattle: @ 82950AA
	.string "I'm training to run from RUSTBORO\n"
	.string "to LAVARIDGE. I need to get ripped!$"

Route103_Text_IsabelleIntro: @ 8295116
	.string "I have the cutest POKéMON!\n"
	.string "Let me show you!$"

Route103_Text_IsabelleDefeated: @ 8295146
	.string "You're mean!$"

Route103_Text_IsabellePostBattle: @ 829514D
	.string "I like splashing in the water. It\n"
	.string "tickles my feet!$"

Route103_Text_RhettIntro: @ 8295199
// >