< //
DewfordTown_Text_BrineyLandedInSlateportDeliverGoods: @ 81EEC1D
	.string "MR. BRINEY: Ahoy!\n"
	.string "We've made land in SLATEPORT!\p"
	.string "I suppose you're going to visit CAPT.\n"
	.string "STERN and deliver the FLASHDRIVE?$"

Route109_Text_BrineySailToDewfordQuestion: @ 81EEC96
	.string "MR. BRINEY: I thought you're supposed\n"
	.string "to deliver the FLASHDRIVE.\p"
	.string "Would you like to sail back to\n"
	.string "DEWFORD, then?$"

Route109_Text_BrineyDewfordItIs: @ 81EED06
	.string "MR. BRINEY: DEWFORD it is, then!\p"
	.string "Anchors aweigh!\n"
	.string "PEEKO, we're setting sail, my darling!$"

Route109_Text_BrineyDeliverDevonGoods: @ 81EED5E
	.string "MR. BRINEY: Then you go on and deliver\n"
	.string "the FLASHDRIVE. I'll be waiting.$"

DewfordTown_Text_BrineyLandedInSlateport: @ 81EEDA7
// >