< //
RustboroCity_Text_WaitDontTakeMyGoods: @ 81E1817
	.string "Wait! Pleeeaaase!\p"
	.string "Don't take my Flashdrive!$"

RustboroCity_Text_HelpMeIWasRobbed: @ 81E183E
	.string "Oh, it's you!\p"
	.string "You're that fantastic TRAINER who\n"
	.string "helped me in PETALBURG WOODS!\p"
	.string "Help me! I was robbed by TEAM MAGMA!\n"
	.string "I have to get the Flashdrive back!\p"
	.string "If I don't…\n"
	.string "I'm going to be in serious trouble.$"

RustboroCity_Text_ShadyCharacterTookOffTowardsTunnel: @ 81E1904
// >

< //
RustboroCity_Text_YouGotItThankYou: @ 81E194D
	.string "Oh! How did it go?\n"
	.string "The Flashdrive?\p"
	.string "You did!\n"
	.string "You got it back!\p"
	.string "You really are a great TRAINER!\p"
	.string "I know! As my thanks, I'll give you\n"
	.string "another GREAT BALL!$"

RustboroCity_Text_YoureLoadedWithItems: @ 81E19E5
// >

< //
RustboroCity_Text_DevonCorpSign: @ 81E2128
	.string "RUSTBORO UNIVERSITY\n"
	.string "“Scientia dux vitae certissimus.”$"

RustboroCity_Text_GymSign: @ 81E2167
// >

< //
RustboroCity_Text_WeShortenItToDevon: @ 81E123F
	.string "The RUSTBORO UNIVERSITY…\n"
	.string "We all just shorten it to UNIVERSITY.\p"
	.string "Their research produces all sorts of\n"
	.string "convenient products.$"

RustboroCity_Text_SneakyLookingManWentAroundCorner: @ 81E12AC
// >