< //
RustboroCity_OnFrame: @ 81E070B
	// disable match call tutorial
	//map_script_2 VAR_RUSTBORO_CITY_STATE, 6, RustboroCity_EventScript_ScientistAddMatchCall
	.2byte 0

RustboroCity_EventScript_ScientistAddMatchCall:: @ 81E0715
// >

< //
RustboroCity_Text_WaitDontTakeMyGoods: @ 81E1817
	.string "Wait! Pleeeaaase!\p"
	.string "Don't take my Flashdrive!$"

RustboroCity_Text_HelpMeIWasRobbed: @ 81E183E
	.string "Oh, it's you!\p"
	.string "You're that fantastic TRAINER who\n"
	.string "helped me in PETALBURG WOODS!\p"
	.string "Help me! I was robbed by TEAM MAGMA!\n"
	.string "I have to get the Flashdrive back!\p"
	.string "If I don't…\n"
	.string "I'm going to be in serious trouble.$"

RustboroCity_Text_ShadyCharacterTookOffTowardsTunnel: @ 81E1904
// >

< //
RustboroCity_Text_YouGotItThankYou: @ 81E194D
	.string "Oh! How did it go?\n"
	.string "The Flashdrive?\p"
	.string "You did!\n"
	.string "You got it back!\p"
	.string "You really are a great TRAINER!\p"
	.string "I know! As my thanks, I'll give you\n"
	.string "another GREAT BALL!$"

RustboroCity_Text_YoureLoadedWithItems: @ 81E19E5
// >

< //
RustboroCity_Text_DevonCorpSign: @ 81E2128
	.string "RUSTBORO UNIVERSITY\n"
	.string "“Scientia dux vitae certissimus.”$"

RustboroCity_Text_GymSign: @ 81E2167
// >

< //
RustboroCity_Text_MayHiLetsRegister: @ 81E1A49
	.string "MAY: Oh, hi, {PLAYER}{KUN}!\p"
	.string "I just realized that we haven't\n"
	.string "been using the POKéNAV!\p"
	.string "Let's register each other so we can\n"
	.string "contact one another anytime!\p"
	.string "… … … … … …$"

RustboroCity_Text_RegisteredMay: @ 81E1ADB
// >

< //
RustboroCity_Text_BrendanHiLetsRegister: @ 81E1D7D
	.string "BRENDAN: Oh, hey, {PLAYER}!\p"
	.string "I just realized that we haven't\n"
	.string "been using the POKéNAV!\p"
	.string "Let's register each other so we can\n"
	.string "get in touch anytime!\p"
	.string "… … … … … …$"

RustboroCity_Text_RegisteredBrendan: @ 81E1E11
// >

< //
RustboroCity_Text_WeShortenItToDevon: @ 81E123F
	.string "The RUSTBORO UNIVERSITY…\n"
	.string "We all just shorten it to UNIVERSITY.\p"
	.string "Their research produces all sorts of\n"
	.string "convenient products.$"

RustboroCity_Text_SneakyLookingManWentAroundCorner: @ 81E12AC
// >